#!/bin/sh

# Start sxhkd if it's not already running
pgrep -x sxhkd >/dev/null || sxhkd &

# Start picom (compositor)
pgrep -x picom >/dev/null || picom --config ~/.config/picom/picom.conf &

# Set up workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9

# Set cursor
xsetroot -cursor_name left_ptr &

# Configure bspwm settings
bspc config normal_border_color "#808080"
bspc config focused_border_color "#ffffff" # Example color, replace with appropriate color

bspc config border_width 1
bspc config window_gap 12
bspc config top_padding 20
bspc config split_ratio 0.5

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

# Start additional startup applications
~/.config/startup.sh &
