[colors.primary]
background = "#000000"

[font]
size = 13

[font.normal]
family = "terminus"
style =  "Bold"

[font.offset]
x = 0
y = 0

[window]
dynamic_padding = false
dynamic_title = true
opacity = 0.7
title = "Alacritty"

[window.padding]
x = 8
y = 10
