[colors]
draw_bold_text_with_bright_colors = false

[colors.primary]
background = "#000000"

[font]
size = 9

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "Fira Code"
style = "Bold"

[font.offset]
x = 0
y = 0

[window]
dynamic_padding = false
dynamic_title = true
opacity = 0.8
title = "Alacritty"

[window.padding]
x = 10
y = 8
